### ISSUE TITLE
Static property cannot be unset

### ISSUE THREAD

**Issue by ghostwriter** [laminas/laminas-cache#107]
>  If a static variable is `unset() `inside of a function, `unset()` destroys the variable only in the context of the rest of a function.  See: [function.unset.php](https://www.php.net/manual/en/function.unset.php)

https://github.com/laminas/laminas-cache/blob/4250fc8611af994066fd4e02ad4af5e1673e5ff1/src/Pattern/ClassCache.php#L149-L160

**Comment by boesing** [comment]
Actually, I see a much bigger problem here and I don't get why this method even exists:

https://3v4l.org/M9pEM

Since this piece of code is like 10 years old, I don't think that even @marc-mabe can remember how that worked 10 years ago 😅

**Comment by marc-mabe** [comment]
Hi,

I think the `ClassCache` pattern should be reviewed in general.
It's usage is quite different than `CallbackCache` and `ObjectCache` because you can't use it as before. Instead you have to replace all static access with object access `Class::method` -> `$cache->method()` & `Class::$prop` -> `$cache->prop`.
This makes it not very useful.
-> I would vote for deprecating the `ClassCache` pattern and remove in 3.0

Beside that it's not possible to set a property to `NULL` if it's a typed property and not nullable as proposed in #108.
A workaround could be to use `ReflectionProperty::getDefaultValue` instead but this also is not unsetting a value but resetting.

**Comment by boesing** [comment]
Thanks Marc, really appreciate your input.

I am +1 on deprecating `ClassCache` while keeping this issue unhandled as it was unhandled for at least 10 years and it only appeared in this issue due to PHPStorm marking the file as invalid I guess?

Correct me if I'm wrong @ghostwriter.
Would that be a valid solution for you as well?

**Comment by boesing** [comment]
Marked as deprecated with #118.
Thanks, @ghostwriter for pointing us on this!
