### ISSUE TITLE
Cannot add laminas cache to my project.

### ISSUE THREAD

**Issue by dejvidecz** [laminas/laminas-cache#189]
### Bug Report

Composer error:
laminas/laminas-cache 3.1.2 requires laminas/laminas-cache-storage-implementation 1.0 -> no matching package found.

#### How to reproduce

Tried in new project:

composer create-project -s dev laminas/laminas-mvc-skeleton path/to/install
Then in folder
composer require laminas/laminas-cache

**Comment by samsonasik** [comment]
You need to install 1 of laminas cache adapter, eg: filesystem:

```bash
composer require laminas/laminas-cache-storage-adapter-filesystem

**Comment by dejvidecz** [comment]
@samsonasik Oh i missed that. Thank you it works.

**Comment by boesing** [comment]
Glad you made it work.
With 3.0 of `laminas-cache`, this component only provides generic cache logic. 
Since this generic cache logic cannot work without an adapter, at least one adapter has to be required by the project as well.

This way, we can easily add new adapters without having releases of this component at all.
