### ISSUE TITLE
RFC: Configure AdapterPluginManager from the config

### ISSUE THREAD

**Issue by rohm1** [laminas/laminas-cache#197]
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | x.y.0  |
| BC Break?           | No |

### Goal

Configure `AdapterPluginManager` from the config.

### Background

Every other service manager laminas provides does have a dedicated configuration key (such as `validators`) but the `AdapterPluginManager` component never had such configuration key.

### Considerations

With this feature we would provide users writing custom cache storage adapters a familiar way of configuring `AdapterPluginManager` while not having to write dedicated delegators.

We also do not need to update the various `laminas/laminas-cache-storage-adapter-XXX` repositories. As @boesing mentioned in https://discourse.laminas.dev/t/configure-storageadapterfactory-from-the-config/2918/4 Laminas ensures internally that the vendor adapters are correctly configured using psalm type annotations.

### Proposal(s)

Declare a `storage_adapters` key in the application config and read it in `StorageAdapterPluginManagerFactory` to initialize the `AdapterPluginManager`. 

```php

final class AdapterPluginManager extends AbstractPluginManager
{
    public const CONFIGURATION_KEY = 'storage_adapters';

    /**
     * Do not share by default
     *
     * @var bool
     */
    protected $sharedByDefault = false;

    /** @var string */
    protected $instanceOf = StorageInterface::class;
}

final class StorageAdapterPluginManagerFactory
{
    public function __invoke(ContainerInterface $container): AdapterPluginManager
    {
        $config = $container->get('config')[AdapterPluginManager::CONFIGURATION_KEY] ?? [];
        return new AdapterPluginManager($container, $config);
    }
}
```

**Comment by froschdesign** [comment]
> Every other service manager laminas provides does have a dedicated configuration key (such as `validators`) but the `laminas/laminas-cache` component never had such configuration key.

Maybe I missed something, but you can use:

```php
'caches' => [
    'example' => [
        'adapter' => [
            'name'    => Laminas\Cache\Storage\Adapter\Filesystem::class,
            'options' => [
                'ttl'       => 7200,
                'cache_dir' => '/data/cache',
            ],
        ],
    ],
],
```

```php
$cache = $container->get('example');
echo $cache->getOptions()->getTtl(); // 7200
```

Because an abstract factory is registered:

https://github.com/laminas/laminas-cache/blob/130cc8db636d97b8287ff817515bb1c9ae0ef099/src/ConfigProvider.php#L40-L42

**Comment by rohm1** [comment]
Hi @froschdesign,
you are talking about creating caches from the config (i.e. which Cache Adapter to use for a given cache name). There is a service manager for Cache Adapters (`AdapterPluginManager`) and it is not possible to register cache adapters from the config (see its factory: https://github.com/laminas/laminas-cache/blob/3.2.x/src/Service/StorageAdapterPluginManagerFactory.php)

----

I've updated the issue as I realized that I mentioned the wrong component name, sorry for the confusion.

**Comment by froschdesign** [comment]
> …I mentioned the wrong component name…

That was the problem. Thanks for the correction!

**Comment by boesing** [comment]
Since this kind of configuration was not possible with v2 of `laminas-cache` either, I'd expected that existing 3rd-party adapters (if any) are already registering themselves via delegator factories.

That was one of the main reasons on why I've chose delegators over configuration arrays. Another reason was to ensure type-safety since its quite easy to fail with array configs which then will trigger that abstract factory.

However, I am open to add some kind of plugin manager configuration via the `config` "service".
Maybe this can be added to [@zakirullin](https://github.com/zakirullin)s [laminas/laminas-servicemanager-inspector](https://github.com/laminas/laminas-servicemanager-inspector) afterwards to help analyzing configurations.

**Comment by froschdesign** [comment]
> Another reason was to ensure type-safety since its quite easy to fail with array configs which then will trigger that abstract factory.

And since arrays do not support auto-completion, it's a mess and pretty useless. _(imo)_

**Comment by Ocramius** [comment]
> And since arrays do not support auto-completion

This kinda works with PHPStan/Psalm array shapes with PHPStorm these days: https://blog.jetbrains.com/phpstorm/2021/07/phpstorm-2021-2-release/#array_shapes_phpdoc_syntax_support

**Comment by froschdesign** [comment]
> This kinda works with PHPStan/Psalm array shapes with PHPStorm these days: https://blog.jetbrains.com/phpstorm/2021/07/phpstorm-2021-2-release/#array_shapes_phpdoc_syntax_support

This is all known, but how does this help in a configuration file? It would be great if we could use this for all packages to enable auto-completion for configuration.

Example: https://docs.laminas.dev/laminas-mvc/quick-start/#create-a-route

**Comment by Ocramius** [comment]
Perhaps via `@psalm-include-type` or such? I'm unsure about IDE support for that.

**Comment by boesing** [comment]
> Perhaps via `@psalm-include-type` or such? I'm unsure about IDE support for that.

That does not work for a PHP file like:

```php
return [
    'storage_adapters' => [
        'factories' => [],
    ],
];
```

This is why there is a config validator for `laminas-cache`:
https://github.com/laminas/laminas-cache/blob/130cc8db636d97b8287ff817515bb1c9ae0ef099/src/Service/StoragePluginFactoryInterface.php#L32

Thats why also suggested to have something like this for `laminas-servicemanager` in one of the PRs since anything else makes it almost impossible to have proper psalm types (which then would benefit here).
